name: Run Safeway Coupons Clipper

on:
  push:
    branches: [main]
    paths:
      - 'src/**/*.ts'
      - '.github/workflows/*.yml'
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  clipper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run Safeway Coupons Clipper
        run: npm run start:prod
        env:
          SAFEWAY_USERNAME: ${{ secrets.SAFEWAY_LOGIN_EMAIL }}
          SAFEWAY_PASSWORD: ${{ secrets.SAFEWAY_LOGIN_PASSWORD }}
          CRAWLEE_VERBOSE_LOG: true
